#!/usr/bin/env python
# -*- coding:utf-8 -*-
from flask_test.minimal_app import app
if __name__ == '__main__':
    app.run(
       host=app.config.get('HOST', '0.0.0.0'),
       port=app.config.get('PORT', 5000),
       debug=app.config['DEBUG'],
    )
